// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbVXU5B9xlcpXR71AjcRWCEoR9xo3C91s',
    appId: '1:292146555837:web:5cb11cf9cc38189677c0d4',
    messagingSenderId: '292146555837',
    projectId: 'geo-tarcks-newfirebase',
    authDomain: 'geo-tarcks-newfirebase.firebaseapp.com',
    storageBucket: 'geo-tarcks-newfirebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWBayKMPu6zDS5J2ssGfbLneRVroRGiEc',
    appId: '1:292146555837:android:729441135a1c5a2277c0d4',
    messagingSenderId: '292146555837',
    projectId: 'geo-tarcks-newfirebase',
    storageBucket: 'geo-tarcks-newfirebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4AOLzAjw-ByCOCYWhK_buF-4es6A2V4Q',
    appId: '1:292146555837:ios:8ed860c14c4b427077c0d4',
    messagingSenderId: '292146555837',
    projectId: 'geo-tarcks-newfirebase',
    storageBucket: 'geo-tarcks-newfirebase.appspot.com',
    iosClientId: '292146555837-spa2eunnf97sbph0oeq4nj28npbno5ta.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
